// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo9uviTbXa0EHeHmh6gKpeYHASIeXt_Fw',
    appId: '1:1009873129842:ios:8f65940f1f24f175798deb',
    messagingSenderId: '1009873129842',
    projectId: 'motorts',
    storageBucket: 'motorts.firebasestorage.app',
    iosBundleId: 'com.example.tp3motorts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMGdCSbvzlwzTWECFgNwH0GKW1NSHi320',
    appId: '1:1009873129842:web:e1dafdf9f0b9e810798deb',
    messagingSenderId: '1009873129842',
    projectId: 'motorts',
    authDomain: 'motorts.firebaseapp.com',
    storageBucket: 'motorts.firebasestorage.app',
    measurementId: 'G-07V6FM785C',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMGdCSbvzlwzTWECFgNwH0GKW1NSHi320',
    appId: '1:1009873129842:web:e1dafdf9f0b9e810798deb',
    messagingSenderId: '1009873129842',
    projectId: 'motorts',
    authDomain: 'motorts.firebaseapp.com',
    storageBucket: 'motorts.firebasestorage.app',
    measurementId: 'G-07V6FM785C',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo9uviTbXa0EHeHmh6gKpeYHASIeXt_Fw',
    appId: '1:1009873129842:ios:8f65940f1f24f175798deb',
    messagingSenderId: '1009873129842',
    projectId: 'motorts',
    storageBucket: 'motorts.firebasestorage.app',
    iosBundleId: 'com.example.tp3motorts',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF8cYujtHU_b_eVJb4UhvJQ0vPr3J4s5c',
    appId: '1:1009873129842:android:46be4d68333bd89c798deb',
    messagingSenderId: '1009873129842',
    projectId: 'motorts',
    storageBucket: 'motorts.firebasestorage.app',
  );
}
